language: generic 

sudo: required
  service:
    - docker

before_install:
  - docker build -t uryadovalex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true uryadovalex/docker-react npm run test
